Update the FOS build to current state of files in FOG working branch as a preperation to entirely move those over to this repo.

diff --git a/Buildroot/board/FOG/FOS/rootfs_overlay/etc/init.d/S40network b/Buildroot/board/FOG/FOS/rootfs_overlay/etc/init.d/S40network
--- a/Buildroot/board/FOG/FOS/rootfs_overlay/etc/init.d/S40network
+++ b/Buildroot/board/FOG/FOS/rootfs_overlay/etc/init.d/S40network
@@ -2,8 +2,6 @@
 #
 # Start the network....
 #
-/usr/bin/psplash-write "MSG Starting Network..."
-/usr/bin/psplash-write "PROGRESS 70"
 if [[ -n $has_usb_nic ]]; then
     echo "Please unplug your device and replug it into the usb port"
     echo -n "Please press enter key to connect [Enter]"
@@ -12,18 +10,18 @@ if [[ -n $has_usb_nic ]]; then
     sleep 5
 fi
 # Enable loopback interface
-/usr/bin/psplash-write "MSG Adding Loopback Device..."
-echo -e "auto lo\niface lo inet loopback\n\n" >> /etc/network/interfaces
+echo -e "auto lo\niface lo inet loopback\n\n" > /etc/network/interfaces
 /sbin/ip addr add 127.0.0.1/8 dev lo
 /sbin/ip link set lo up
 
+sleep 10
+
 # Generated a sorted list with primary interfaces first
-read p_ifaces <<< $(/sbin/ip -0 -o addr show | awk -F'[: ]+' '/link[/]?ether/ && /'$mac'/ {print $2}')
-read o_ifaces <<< $(/sbin/ip -0 -o addr show | awk -F'[: ]+' '/link[/]?ether/ && !/'$mac'/ {print $2}')
+read p_ifaces <<< $(/sbin/ip -0 -o addr show | awk -F'[: ]+' 'tolower($0) ~ /link[/]?ether/ && tolower($0) ~ /'$mac'/ {print $2}' | tr '\n' ' ')
+read o_ifaces <<< $(/sbin/ip -0 -o addr show | awk -F'[: ]+' 'tolower($0) ~ /link[/]?ether/ && tolower($0) !~ /'$mac'/ {print $2}' | tr '\n' ' ')
 ifaces="$p_ifaces $o_ifaces"
 for iface in $ifaces; do
     echo "Starting $iface interface and waiting for the link to come up"
-    /usr/bin/psplash-write "MSG Starting ${iface}..."
     echo -e "auto $iface\niface $iface inet dhcp\n\n" >> /etc/network/interfaces
     /sbin/ip link set $iface up
 
@@ -38,10 +36,15 @@ for iface in $ifaces; do
     [[ $linkstate -eq 0 ]] && echo "No link detected on $iface for $timeout seconds, skipping it." && continue
     for retry in $(seq 3); do
         /sbin/udhcpc -i $iface --now
-        if [[ $? -eq 0 ]]; then
-            /usr/bin/psplash-write "MSG Started Network"
-            exit 0
-        fi
+        ustat="$?"
+        curl -Ikfso /dev/null "${web}"/index.php --connect-timeout 5
+        cstat="$?"
+        # If the udhcp is okay AND we can curl our web
+        # we know we have link so no need to continue on.
+        # NOTE: the link to web is kind of important, just
+        # exiting on dhcp request is not sufficient.
+        [[ $ustat -eq 0 && $cstat -eq 0 ]] && exit 0
+        echo "Either DHCP failed or we were unable to access ${web}/index.php for connection testing."
         sleep 1
     done
     echo "No DHCP response on interface $iface, skipping it."
